# Generated by Django 3.2.9 on 2021-11-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empNo', models.IntegerField()),
                ('empName', models.CharField(max_length=100)),
                ('empSalary', models.IntegerField()),
                ('empAddress', models.CharField(max_length=200)),
            ],
        ),
    ]
